// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC98LUUaEKKCKZzIW8_0Q8ScD2UhzzpggE',
    appId: '1:354580763022:web:00fba29e4990ac7273d4df',
    messagingSenderId: '354580763022',
    projectId: 'flutter-auth-588b3',
    authDomain: 'flutter-auth-588b3.firebaseapp.com',
    storageBucket: 'flutter-auth-588b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkCRuYXfQiki3MEm9FNLHT0_KJmuGk6aY',
    appId: '1:354580763022:android:b3329e5d11c33cda73d4df',
    messagingSenderId: '354580763022',
    projectId: 'flutter-auth-588b3',
    storageBucket: 'flutter-auth-588b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp8iVwhBalHiMaABpXQfpsXrLo4vJSscY',
    appId: '1:354580763022:ios:94e822009b9f85ab73d4df',
    messagingSenderId: '354580763022',
    projectId: 'flutter-auth-588b3',
    storageBucket: 'flutter-auth-588b3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp8iVwhBalHiMaABpXQfpsXrLo4vJSscY',
    appId: '1:354580763022:ios:94e822009b9f85ab73d4df',
    messagingSenderId: '354580763022',
    projectId: 'flutter-auth-588b3',
    storageBucket: 'flutter-auth-588b3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC98LUUaEKKCKZzIW8_0Q8ScD2UhzzpggE',
    appId: '1:354580763022:web:35014e13be6bacfc73d4df',
    messagingSenderId: '354580763022',
    projectId: 'flutter-auth-588b3',
    authDomain: 'flutter-auth-588b3.firebaseapp.com',
    storageBucket: 'flutter-auth-588b3.firebasestorage.app',
  );
}
